import type { NanoBite } from '../types';

// Phase 3a — Grocer operational nano-bites
export const GROCER_BITES: NanoBite[] = [
  { id: 'grocer.club.member', industryId: 'tertiary.grocer.club_store', valueChainStage: 'marketing_sales', microElement: "Membership", task: "Validate member ID at entry / POS", cadence: 'event', automatable: true },
  { id: 'grocer.club.bulk', industryId: 'tertiary.grocer.club_store', valueChainStage: 'operations', microElement: "Bulk Pricing", task: "Apply bulk-pack pricing rules at POS", cadence: 'event', automatable: true },
  { id: 'grocer.club.pallet', industryId: 'tertiary.grocer.club_store', valueChainStage: 'inbound_logistics', microElement: "Pallet Receive", task: "Pallet-level receiving (no break-pack)", cadence: 'daily', automatable: true },
  { id: 'grocer.club.shrink', industryId: 'tertiary.grocer.club_store', valueChainStage: 'operations', microElement: "Shrink", task: "Daily shrink reconciliation", cadence: 'daily', automatable: true },
  { id: 'grocer.club.fuel', industryId: 'tertiary.grocer.club_store', valueChainStage: 'operations', microElement: "Fuel Pump", task: "Sync fuel pump dispense to POS", cadence: 'daily', automatable: true },
  { id: 'grocer.mkt.vendor', industryId: 'tertiary.grocer.marketplace', valueChainStage: 'procurement', microElement: "Vendor Stall", task: "Vendor stall settlement & rent", cadence: 'weekly', automatable: true },
  { id: 'grocer.mkt.weighed', industryId: 'tertiary.grocer.marketplace', valueChainStage: 'operations', microElement: "Weighed Goods", task: "Scale-tied price lookup at POS", cadence: 'event', automatable: true },
  { id: 'grocer.mkt.cash', industryId: 'tertiary.grocer.marketplace', valueChainStage: 'operations', microElement: "Cash Reconcile", task: "End-of-day cash drawer per stall", cadence: 'daily', automatable: true },
  { id: 'grocer.mkt.tax', industryId: 'tertiary.grocer.marketplace', valueChainStage: 'infrastructure', microElement: "Tax Class", task: "Per-vendor tax class mapping", cadence: 'weekly', automatable: true },
  { id: 'grocer.sup.dept', industryId: 'tertiary.grocer.super_center', valueChainStage: 'operations', microElement: "Dept Margin", task: "Department-level margin report", cadence: 'daily', automatable: true },
  { id: 'grocer.sup.planogram', industryId: 'tertiary.grocer.super_center', valueChainStage: 'marketing_sales', microElement: "Planogram", task: "Planogram compliance audit", cadence: 'weekly', automatable: true },
  { id: 'grocer.sup.bopis', industryId: 'tertiary.grocer.super_center', valueChainStage: 'outbound_logistics', microElement: "BOPIS", task: "Buy-online-pick-up-in-store fulfillment queue", cadence: 'daily', automatable: true },
  { id: 'grocer.sup.shrink', industryId: 'tertiary.grocer.super_center', valueChainStage: 'operations', microElement: "Shrink", task: "Cross-dept shrink trend", cadence: 'weekly', automatable: true },
  { id: 'grocer.sup.dsd', industryId: 'tertiary.grocer.super_center', valueChainStage: 'inbound_logistics', microElement: "DSD", task: "Direct-Store-Delivery vendor check-in", cadence: 'daily', automatable: true },
  { id: 'grocer.cv.shift', industryId: 'tertiary.grocer.convenience', valueChainStage: 'operations', microElement: "Shift Handoff", task: "Shift change cash drop & log", cadence: 'daily', automatable: true },
  { id: 'grocer.cv.lottery', industryId: 'tertiary.grocer.convenience', valueChainStage: 'operations', microElement: "Lottery", task: "Lottery inventory reconcile", cadence: 'daily', automatable: true },
  { id: 'grocer.cv.fuel', industryId: 'tertiary.grocer.convenience', valueChainStage: 'operations', microElement: "Fuel Sync", task: "Forecourt-to-POS fuel reconcile", cadence: 'daily', automatable: true },
  { id: 'grocer.cv.age', industryId: 'tertiary.grocer.convenience', valueChainStage: 'operations', microElement: "Age Verify", task: "ID-scan age verification for restricted goods", cadence: 'event', automatable: true },
  { id: 'grocer.cv.foodservice', industryId: 'tertiary.grocer.convenience', valueChainStage: 'operations', microElement: "Food Service", task: "Roller-grill / coffee waste log", cadence: 'daily', automatable: true },
  { id: 'grocer.org.coa', industryId: 'tertiary.grocer.organic_natural', valueChainStage: 'inbound_logistics', microElement: "COA", task: "Certificate-of-Analysis intake", cadence: 'event', automatable: true, requiresTier: 'pro' },
  { id: 'grocer.org.cert', industryId: 'tertiary.grocer.organic_natural', valueChainStage: 'infrastructure', microElement: "Organic Cert", task: "USDA Organic certification audit log", cadence: 'monthly', automatable: true, requiresTier: 'pro' },
  { id: 'grocer.org.local', industryId: 'tertiary.grocer.organic_natural', valueChainStage: 'marketing_sales', microElement: "Local Source", task: "Tag local-sourced SKUs at shelf", cadence: 'weekly', automatable: true },
  { id: 'grocer.org.bulk', industryId: 'tertiary.grocer.organic_natural', valueChainStage: 'operations', microElement: "Bulk Bin", task: "Bulk-bin tare + price-per-oz", cadence: 'event', automatable: true },
  { id: 'grocer.org.expiry', industryId: 'tertiary.grocer.organic_natural', valueChainStage: 'operations', microElement: "Short Code", task: "Short-code markdown automation", cadence: 'daily', automatable: true },
  { id: 'grocer.but.cut', industryId: 'tertiary.grocer.butcher_shop', valueChainStage: 'operations', microElement: "Cut Sheet", task: "Whole-animal cut sheet yield", cadence: 'event', automatable: true },
  { id: 'grocer.but.trace', industryId: 'tertiary.grocer.butcher_shop', valueChainStage: 'infrastructure', microElement: "Traceability", task: "Lot/farm traceability per cut", cadence: 'event', automatable: true, requiresTier: 'pro' },
  { id: 'grocer.but.weigh', industryId: 'tertiary.grocer.butcher_shop', valueChainStage: 'operations', microElement: "Weigh-Price", task: "Weigh-and-price label printer", cadence: 'event', automatable: true },
  { id: 'grocer.but.haccp', industryId: 'tertiary.grocer.butcher_shop', valueChainStage: 'infrastructure', microElement: "HACCP", task: "Daily temp + sanitation log", cadence: 'daily', automatable: true, requiresTier: 'pro' },
  { id: 'grocer.but.special', industryId: 'tertiary.grocer.butcher_shop', valueChainStage: 'marketing_sales', microElement: "Special Order", task: "Custom cut special-order queue", cadence: 'event', automatable: true },
];
