import type { NanoBite } from '../types';
export const HOSPITALITY_BITES: NanoBite[] = [
  { id: 'hosp.ops.greet', industryId: 'tertiary.hospitality', valueChainStage: 'service',    microElement: 'Front of House', task: 'Customer greeting protocol', cadence: 'daily', automatable: false },
  { id: 'hosp.ops.turn',  industryId: 'tertiary.hospitality', valueChainStage: 'operations', microElement: 'Housekeeping',   task: 'Room turn cycle', cadence: 'daily', automatable: false },
  // ── Spatial Telemetry bites (validated by validateSpatialEvent in telemetry.ts) ──
  { id: 'hosp.ops.guest_flow_tracking', industryId: 'tertiary.hospitality', valueChainStage: 'operations',     microElement: 'Spatial AI Navigation', task: 'Execute Adaptive Monte Carlo Localization for guest floor traversal', cadence: 'daily', automatable: true,  requiresTier: 'enterprise' },
  { id: 'hosp.service.proximity_greeting', industryId: 'tertiary.hospitality', valueChainStage: 'service',     microElement: 'UWB Proximity',         task: 'Trigger guest-experience greeting via UWB tag detection',             cadence: 'event', automatable: false, requiresTier: 'pro' },
  { id: 'hosp.ops.kitchen_telemetry',   industryId: 'tertiary.hospitality', valueChainStage: 'operations',    microElement: 'Kitchen Automation',     task: 'Monitor Speed-of-Service (SoS) via kitchen display telemetry',         cadence: 'event', automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.infra.spatial_audit',     industryId: 'tertiary.hospitality', valueChainStage: 'infrastructure', microElement: 'LiDAR Mapping',         task: 'Update Property Management System (PMS) via mobile LiDAR scan',       cadence: 'monthly', automatable: false, requiresTier: 'enterprise' },
  // ── Hotel & Property Management (PMS) sub-vertical ──
  { id: 'hosp.lodging.reservations.unified_calendar', industryId: 'tertiary.hospitality.lodging', valueChainStage: 'operations',   microElement: 'Reservation Management', task: 'Sync OTA, direct, and walk-in bookings into a single inventory calendar to prevent overbookings', cadence: 'event',  automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.lodging.frontdesk.auto_checkin',        industryId: 'tertiary.hospitality.lodging', valueChainStage: 'service',      microElement: 'Front Desk',             task: 'Automated check-in and check-out flow with mobile key issuance',                                cadence: 'event',  automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.lodging.frontdesk.room_assignment',     industryId: 'tertiary.hospitality.lodging', valueChainStage: 'operations',   microElement: 'Front Desk',             task: 'Optimize room assignment by guest preference and turn status',                                  cadence: 'event',  automatable: true,  requiresTier: 'basic' },
  { id: 'hosp.lodging.housekeeping.status_board',     industryId: 'tertiary.hospitality.lodging', valueChainStage: 'operations',   microElement: 'Housekeeping',           task: 'Real-time clean / dirty / inspected room status from mobile updates',                          cadence: 'event',  automatable: true,  requiresTier: 'basic' },
  { id: 'hosp.lodging.maintenance.work_orders',       industryId: 'tertiary.hospitality.lodging', valueChainStage: 'operations',   microElement: 'Maintenance',            task: 'Open, route, and close maintenance tickets tied to a room or asset',                            cadence: 'event',  automatable: true,  requiresTier: 'basic' },
  { id: 'hosp.lodging.crm.guest_profile',             industryId: 'tertiary.hospitality.lodging', valueChainStage: 'marketing_sales', microElement: 'Guest CRM',           task: 'Centralize guest history, preferences, and stay notes (PII-free identifiers only)',             cadence: 'daily',  automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.lodging.revenue.dynamic_rates',         industryId: 'tertiary.hospitality.lodging', valueChainStage: 'marketing_sales', microElement: 'Revenue Management',  task: 'Push dynamic ADR / occupancy-driven rates across all distribution channels',                    cadence: 'daily',  automatable: true,  requiresTier: 'enterprise' },
  { id: 'hosp.lodging.billing.guest_folio',           industryId: 'tertiary.hospitality.lodging', valueChainStage: 'service',      microElement: 'Billing',                task: 'Maintain guest folio with split charges and secure payment capture',                            cadence: 'event',  automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.lodging.finance.gl_export',             industryId: 'tertiary.hospitality.lodging', valueChainStage: 'infrastructure', microElement: 'Financial Integration', task: 'Export folio activity to the accounting general ledger',                                       cadence: 'weekly', automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.lodging.analytics.occupancy_revpar',    industryId: 'tertiary.hospitality.lodging', valueChainStage: 'technology',   microElement: 'Reporting',              task: 'Generate ADR, occupancy, and RevPAR performance reports',                                       cadence: 'daily',  automatable: true,  requiresTier: 'enterprise' },
  { id: 'hosp.lodging.integrations.channel_pos',      industryId: 'tertiary.hospitality.lodging', valueChainStage: 'technology',   microElement: 'Integrations',           task: 'Maintain connections to channel managers, booking engines, and on-property POS',                cadence: 'daily',  automatable: true,  requiresTier: 'enterprise' },
  // ── High-Volume Bar & Nightlife sub-vertical ──
  { id: 'hosp.bar.tabs.preauth_hold',          industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'service',         microElement: 'Tab Management',  task: 'Place pre-authorization hold on card to prevent walkouts',                            cadence: 'event', automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.bar.tabs.quick_access',          industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'service',         microElement: 'Tab Management',  task: 'Open and recall tabs by name or seat number with macro buttons',                      cadence: 'event', automatable: false, requiresTier: 'basic' },
  { id: 'hosp.bar.order.modifier_swap',        industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'operations',      microElement: 'Order Entry',     task: 'Mid-order spirit / mixer swap without restarting the ticket',                         cadence: 'event', automatable: false, requiresTier: 'basic' },
  { id: 'hosp.bar.recipe.lookup',              industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'operations',      microElement: 'Recipe Engine',   task: 'Surface canonical drink recipe at the well for pour consistency',                     cadence: 'event', automatable: false, requiresTier: 'pro' },
  { id: 'hosp.bar.inventory.pour_tracking',    industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'inbound_logistics', microElement: 'Pour Tracking', task: 'Capture liquid volume (oz / ml) from scale or flow meter for every pour',             cadence: 'event', automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.bar.inventory.recipe_costing',   industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'operations',      microElement: 'Cost Control',    task: 'Auto-deduct fluid ounces from inventory using recipe yields',                         cadence: 'event', automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.bar.pricing.happy_hour_window',  industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'marketing_sales', microElement: 'Dynamic Pricing', task: 'Apply time-windowed Happy Hour pricing automatically',                                 cadence: 'event', automatable: true,  requiresTier: 'basic' },
  { id: 'hosp.bar.pricing.amenity_time_charge', industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'marketing_sales', microElement: 'Dynamic Pricing', task: 'Bill time-based amenity usage (table, simulator, lane) by the minute',               cadence: 'event', automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.bar.analytics.pour_variance',    industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'technology',      microElement: 'Analytics',       task: 'Reconcile poured vs. sold volume and flag variance',                                  cadence: 'daily', automatable: true,  requiresTier: 'enterprise' },
];
