import type { NanoBite } from '../types';
export const HOSPITALITY_BITES: NanoBite[] = [
  { id: 'hosp.ops.greet', industryId: 'tertiary.hospitality', valueChainStage: 'service',    microElement: 'Front of House', task: 'Customer greeting protocol', cadence: 'daily', automatable: false },
  { id: 'hosp.ops.turn',  industryId: 'tertiary.hospitality', valueChainStage: 'operations', microElement: 'Housekeeping',   task: 'Room turn cycle', cadence: 'daily', automatable: false },
  // ── Spatial Telemetry bites (validated by validateSpatialEvent in telemetry.ts) ──
  { id: 'hosp.ops.guest_flow_tracking', industryId: 'tertiary.hospitality', valueChainStage: 'operations',     microElement: 'Spatial AI Navigation', task: 'Execute Adaptive Monte Carlo Localization for guest floor traversal', cadence: 'daily', automatable: true,  requiresTier: 'enterprise' },
  { id: 'hosp.service.proximity_greeting', industryId: 'tertiary.hospitality', valueChainStage: 'service',     microElement: 'UWB Proximity',         task: 'Trigger guest-experience greeting via UWB tag detection',             cadence: 'event', automatable: false, requiresTier: 'pro' },
  { id: 'hosp.ops.kitchen_telemetry',   industryId: 'tertiary.hospitality', valueChainStage: 'operations',    microElement: 'Kitchen Automation',     task: 'Monitor Speed-of-Service (SoS) via kitchen display telemetry',         cadence: 'event', automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.infra.spatial_audit',     industryId: 'tertiary.hospitality', valueChainStage: 'infrastructure', microElement: 'LiDAR Mapping',         task: 'Update Property Management System (PMS) via mobile LiDAR scan',       cadence: 'monthly', automatable: false, requiresTier: 'enterprise' },
  // ── Hotel & Property Management (PMS) sub-vertical ──
  { id: 'hosp.lodging.reservations.unified_calendar', industryId: 'tertiary.hospitality.lodging', valueChainStage: 'operations',   microElement: 'Reservation Management', task: 'Sync OTA, direct, and walk-in bookings into a single inventory calendar to prevent overbookings', cadence: 'event',  automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.lodging.frontdesk.auto_checkin',        industryId: 'tertiary.hospitality.lodging', valueChainStage: 'service',      microElement: 'Front Desk',             task: 'Automated check-in and check-out flow with mobile key issuance',                                cadence: 'event',  automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.lodging.frontdesk.room_assignment',     industryId: 'tertiary.hospitality.lodging', valueChainStage: 'operations',   microElement: 'Front Desk',             task: 'Optimize room assignment by guest preference and turn status',                                  cadence: 'event',  automatable: true,  requiresTier: 'basic' },
  { id: 'hosp.lodging.housekeeping.status_board',     industryId: 'tertiary.hospitality.lodging', valueChainStage: 'operations',   microElement: 'Housekeeping',           task: 'Real-time clean / dirty / inspected room status from mobile updates',                          cadence: 'event',  automatable: true,  requiresTier: 'basic' },
  { id: 'hosp.lodging.maintenance.work_orders',       industryId: 'tertiary.hospitality.lodging', valueChainStage: 'operations',   microElement: 'Maintenance',            task: 'Open, route, and close maintenance tickets tied to a room or asset',                            cadence: 'event',  automatable: true,  requiresTier: 'basic' },
  { id: 'hosp.lodging.crm.guest_profile',             industryId: 'tertiary.hospitality.lodging', valueChainStage: 'marketing_sales', microElement: 'Guest CRM',           task: 'Centralize guest history, preferences, and stay notes (PII-free identifiers only)',             cadence: 'daily',  automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.lodging.revenue.dynamic_rates',         industryId: 'tertiary.hospitality.lodging', valueChainStage: 'marketing_sales', microElement: 'Revenue Management',  task: 'Push dynamic ADR / occupancy-driven rates across all distribution channels',                    cadence: 'daily',  automatable: true,  requiresTier: 'enterprise' },
  { id: 'hosp.lodging.billing.guest_folio',           industryId: 'tertiary.hospitality.lodging', valueChainStage: 'service',      microElement: 'Billing',                task: 'Maintain guest folio with split charges and secure payment capture',                            cadence: 'event',  automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.lodging.finance.gl_export',             industryId: 'tertiary.hospitality.lodging', valueChainStage: 'infrastructure', microElement: 'Financial Integration', task: 'Export folio activity to the accounting general ledger',                                       cadence: 'weekly', automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.lodging.analytics.occupancy_revpar',    industryId: 'tertiary.hospitality.lodging', valueChainStage: 'technology',   microElement: 'Reporting',              task: 'Generate ADR, occupancy, and RevPAR performance reports',                                       cadence: 'daily',  automatable: true,  requiresTier: 'enterprise' },
  { id: 'hosp.lodging.integrations.channel_pos',      industryId: 'tertiary.hospitality.lodging', valueChainStage: 'technology',   microElement: 'Integrations',           task: 'Maintain connections to channel managers, booking engines, and on-property POS',                cadence: 'daily',  automatable: true,  requiresTier: 'enterprise' },
  // ── High-Volume Bar & Nightlife sub-vertical ──
  { id: 'hosp.bar.tabs.preauth_hold',          industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'service',         microElement: 'Tab Management',  task: 'Place pre-authorization hold on card to prevent walkouts',                            cadence: 'event', automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.bar.tabs.quick_access',          industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'service',         microElement: 'Tab Management',  task: 'Open and recall tabs by name or seat number with macro buttons',                      cadence: 'event', automatable: false, requiresTier: 'basic' },
  { id: 'hosp.bar.order.modifier_swap',        industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'operations',      microElement: 'Order Entry',     task: 'Mid-order spirit / mixer swap without restarting the ticket',                         cadence: 'event', automatable: false, requiresTier: 'basic' },
  { id: 'hosp.bar.recipe.lookup',              industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'operations',      microElement: 'Recipe Engine',   task: 'Surface canonical drink recipe at the well for pour consistency',                     cadence: 'event', automatable: false, requiresTier: 'pro' },
  { id: 'hosp.bar.inventory.pour_tracking',    industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'inbound_logistics', microElement: 'Pour Tracking', task: 'Capture liquid volume (oz / ml) from scale or flow meter for every pour',             cadence: 'event', automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.bar.inventory.recipe_costing',   industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'operations',      microElement: 'Cost Control',    task: 'Auto-deduct fluid ounces from inventory using recipe yields',                         cadence: 'event', automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.bar.pricing.happy_hour_window',  industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'marketing_sales', microElement: 'Dynamic Pricing', task: 'Apply time-windowed Happy Hour pricing automatically',                                 cadence: 'event', automatable: true,  requiresTier: 'basic' },
  { id: 'hosp.bar.pricing.amenity_time_charge', industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'marketing_sales', microElement: 'Dynamic Pricing', task: 'Bill time-based amenity usage (table, simulator, lane) by the minute',               cadence: 'event', automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.bar.analytics.pour_variance',    industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'technology',      microElement: 'Analytics',       task: 'Reconcile poured vs. sold volume and flag variance',                                  cadence: 'daily', automatable: true,  requiresTier: 'enterprise' },
  // ── Fine Dining ──
  { id: 'hosp.fd.reservation', industryId: 'tertiary.hospitality.fine_dining', valueChainStage: 'operations',      microElement: 'Reservation', task: 'Reservation & deposit management',          cadence: 'daily', automatable: true },
  { id: 'hosp.fd.coursing',    industryId: 'tertiary.hospitality.fine_dining', valueChainStage: 'operations',      microElement: 'Coursing',    task: 'Multi-course pacing & fire',                cadence: 'event', automatable: true, requiresTier: 'pro' },
  { id: 'hosp.fd.wine',        industryId: 'tertiary.hospitality.fine_dining', valueChainStage: 'inbound_logistics', microElement: 'Wine List', task: 'Wine-list & cellar inventory',              cadence: 'weekly', automatable: true, requiresTier: 'pro' },
  { id: 'hosp.fd.tipout',      industryId: 'tertiary.hospitality.fine_dining', valueChainStage: 'marketing_sales', microElement: 'Tip Pool',    task: 'Tip-pool distribution',                     cadence: 'daily', automatable: true },
  { id: 'hosp.fd.guest',       industryId: 'tertiary.hospitality.fine_dining', valueChainStage: 'service',         microElement: 'Guest CRM',   task: 'VIP & allergen guest profile',              cadence: 'daily', automatable: true, requiresTier: 'pro' },
  // ── Diner ──
  { id: 'hosp.dn.tableturn',   industryId: 'tertiary.hospitality.diner', valueChainStage: 'operations',     microElement: 'Table Turn',  task: 'Table-turn time tracking',         cadence: 'daily', automatable: true },
  { id: 'hosp.dn.allday',      industryId: 'tertiary.hospitality.diner', valueChainStage: 'operations',     microElement: 'All-day Menu',task: 'All-day menu + breakfast switch',  cadence: 'daily', automatable: true },
  { id: 'hosp.dn.tabs',        industryId: 'tertiary.hospitality.diner', valueChainStage: 'service',        microElement: 'Tab',         task: 'Counter & booth tab merge',        cadence: 'event', automatable: true },
  { id: 'hosp.dn.tipout',      industryId: 'tertiary.hospitality.diner', valueChainStage: 'marketing_sales',microElement: 'Tip Out',     task: 'Server tip-out split',             cadence: 'daily', automatable: true },
  { id: 'hosp.dn.loyalty',     industryId: 'tertiary.hospitality.diner', valueChainStage: 'marketing_sales',microElement: 'Loyalty',     task: 'Frequent-diner punch loyalty',     cadence: 'event', automatable: true },
  // ── Home Services ──
  { id: 'hosp.hs.dispatch',    industryId: 'tertiary.hospitality.home_services', valueChainStage: 'operations',     microElement: 'Dispatch', task: 'Tech dispatch & ETA',          cadence: 'daily', automatable: true },
  { id: 'hosp.hs.quote',       industryId: 'tertiary.hospitality.home_services', valueChainStage: 'marketing_sales',microElement: 'Quote',    task: 'On-site quote & approval',     cadence: 'event', automatable: true },
  { id: 'hosp.hs.recurring',   industryId: 'tertiary.hospitality.home_services', valueChainStage: 'marketing_sales',microElement: 'Recurring',task: 'Recurring service plan',       cadence: 'monthly', automatable: true },
  { id: 'hosp.hs.photo',       industryId: 'tertiary.hospitality.home_services', valueChainStage: 'service',        microElement: 'Photo Proof', task: 'Before/after photo proof',  cadence: 'event', automatable: true },
  { id: 'hosp.hs.review',      industryId: 'tertiary.hospitality.home_services', valueChainStage: 'service',        microElement: 'Review',   task: 'Post-service review request',  cadence: 'event', automatable: true },
  // ── Theme Park ──
  { id: 'hosp.tp.ticket',      industryId: 'tertiary.hospitality.theme_park', valueChainStage: 'marketing_sales',microElement: 'Ticket',     task: 'Ticket & multi-day pass scan',     cadence: 'daily', automatable: true },
  { id: 'hosp.tp.queue',       industryId: 'tertiary.hospitality.theme_park', valueChainStage: 'operations',     microElement: 'Queue',      task: 'Virtual queue / fast-pass',        cadence: 'daily', automatable: true, requiresTier: 'pro' },
  { id: 'hosp.tp.foodbev',     industryId: 'tertiary.hospitality.theme_park', valueChainStage: 'service',        microElement: 'F&B',        task: 'In-park F&B mobile order',         cadence: 'daily', automatable: true },
  { id: 'hosp.tp.merch',       industryId: 'tertiary.hospitality.theme_park', valueChainStage: 'service',        microElement: 'Merch',      task: 'Park-wide merch ship-to-home',     cadence: 'daily', automatable: true },
  { id: 'hosp.tp.safety',      industryId: 'tertiary.hospitality.theme_park', valueChainStage: 'infrastructure', microElement: 'Ride Safety',task: 'Ride pre-op safety checklist',     cadence: 'daily', automatable: true, requiresTier: 'enterprise' },
  // ── Café & Bakery ──
  { id: 'hosp.cb.openclose',   industryId: 'tertiary.hospitality.cafe_bakery', valueChainStage: 'operations',     microElement: 'Open/Close', task: 'Open/close cash & prep checklist', cadence: 'daily', automatable: true },
  { id: 'hosp.cb.bake',        industryId: 'tertiary.hospitality.cafe_bakery', valueChainStage: 'operations',     microElement: 'Bake List',  task: 'Daily bake list from forecast',    cadence: 'daily', automatable: true, requiresTier: 'pro' },
  { id: 'hosp.cb.preorder',    industryId: 'tertiary.hospitality.cafe_bakery', valueChainStage: 'service',        microElement: 'Pre-order',  task: 'Cake / catering pre-order',        cadence: 'event', automatable: true },
  { id: 'hosp.cb.loyalty',     industryId: 'tertiary.hospitality.cafe_bakery', valueChainStage: 'marketing_sales',microElement: 'Loyalty',    task: 'Beverage loyalty stamp',           cadence: 'event', automatable: true },
  { id: 'hosp.cb.waste',       industryId: 'tertiary.hospitality.cafe_bakery', valueChainStage: 'operations',     microElement: 'Waste Log',  task: 'End-of-day waste log',             cadence: 'daily', automatable: true },
  // ── Catering ──
  { id: 'hosp.cat.event',      industryId: 'tertiary.hospitality.catering', valueChainStage: 'operations',      microElement: 'Event Order',task: 'Banquet-event order (BEO)',        cadence: 'event', automatable: true, requiresTier: 'pro' },
  { id: 'hosp.cat.proposal',   industryId: 'tertiary.hospitality.catering', valueChainStage: 'marketing_sales', microElement: 'Proposal',   task: 'Quote & proposal generation',      cadence: 'event', automatable: true },
  { id: 'hosp.cat.staffing',   industryId: 'tertiary.hospitality.catering', valueChainStage: 'human_resources', microElement: 'Staffing',   task: 'Event-staffing assignment',        cadence: 'event', automatable: true },
  { id: 'hosp.cat.delivery',   industryId: 'tertiary.hospitality.catering', valueChainStage: 'outbound_logistics', microElement: 'Delivery',task: 'Hot-box load & delivery route',   cadence: 'event', automatable: true },
  { id: 'hosp.cat.invoice',    industryId: 'tertiary.hospitality.catering', valueChainStage: 'marketing_sales', microElement: 'Invoice',    task: 'Final-count invoice & gratuity',   cadence: 'event', automatable: true },
  // ============================================================
  // PMS DENSITY — Hotel Property Management essentials
  // ============================================================
  { id: 'hosp.lodging.reservations.modify_cancel',  industryId: 'tertiary.hospitality.lodging', valueChainStage: 'operations',      microElement: 'Reservation Management', task: 'Modify or cancel reservation with policy enforcement and refund hooks', cadence: 'event',   automatable: true,  requiresTier: 'basic' },
  { id: 'hosp.lodging.reservations.deposit_capture',industryId: 'tertiary.hospitality.lodging', valueChainStage: 'marketing_sales', microElement: 'Reservation Management', task: 'Capture and hold reservation deposit per cancellation policy',          cadence: 'event',   automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.lodging.frontdesk.keycard_issue',     industryId: 'tertiary.hospitality.lodging', valueChainStage: 'service',         microElement: 'Front Desk',             task: 'Encode and revoke RFID / mobile key card on assignment and checkout',   cadence: 'event',   automatable: true,  requiresTier: 'basic' },
  { id: 'hosp.lodging.billing.payment_processing',  industryId: 'tertiary.hospitality.lodging', valueChainStage: 'service',         microElement: 'Billing',                task: 'PCI-compliant card capture and tokenization at folio',                  cadence: 'event',   automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.lodging.billing.split_charges',       industryId: 'tertiary.hospitality.lodging', valueChainStage: 'service',         microElement: 'Billing',                task: 'Split folio across guests, companies, and payment methods',             cadence: 'event',   automatable: true,  requiresTier: 'basic' },
  { id: 'hosp.lodging.billing.invoice_generation',  industryId: 'tertiary.hospitality.lodging', valueChainStage: 'service',         microElement: 'Billing',                task: 'Auto-generate and email guest invoice / receipt on checkout',           cadence: 'event',   automatable: true,  requiresTier: 'basic' },
  { id: 'hosp.lodging.crm.preferences_history',     industryId: 'tertiary.hospitality.lodging', valueChainStage: 'marketing_sales', microElement: 'Guest CRM',              task: 'Persist stay history, room preferences, and allergen flags (PII-free identifiers)', cadence: 'daily', automatable: true, requiresTier: 'pro' },
  { id: 'hosp.lodging.crm.pre_arrival_comms',       industryId: 'tertiary.hospitality.lodging', valueChainStage: 'marketing_sales', microElement: 'Guest CRM',              task: 'Automated pre-arrival and confirmation emails with templated content',  cadence: 'event',   automatable: true,  requiresTier: 'basic' },
  { id: 'hosp.lodging.analytics.night_audit',       industryId: 'tertiary.hospitality.lodging', valueChainStage: 'technology',      microElement: 'Reporting',              task: 'Run nightly close: post room/tax, roll business date, lock prior day',  cadence: 'daily',   automatable: true,  requiresTier: 'basic' },
  { id: 'hosp.lodging.analytics.shift_audit',       industryId: 'tertiary.hospitality.lodging', valueChainStage: 'technology',      microElement: 'Reporting',              task: 'Generate cashier / front-desk shift audit report',                      cadence: 'daily',   automatable: true,  requiresTier: 'basic' },
  { id: 'hosp.lodging.analytics.tax_report',        industryId: 'tertiary.hospitality.lodging', valueChainStage: 'technology',      microElement: 'Reporting',              task: 'Room and tax revenue report by jurisdiction',                           cadence: 'daily',   automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.lodging.integrations.pos_room_charge',industryId: 'tertiary.hospitality.lodging', valueChainStage: 'technology',      microElement: 'Integrations',           task: 'Allow on-property POS to post charges directly to the active guest folio', cadence: 'event', automatable: true, requiresTier: 'pro' },
  // ============================================================
  // BAR & RESTAURANT POS DENSITY
  // ============================================================
  { id: 'hosp.bar.order.tableside_handheld',  industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'service',           microElement: 'Order Entry',     task: 'Take orders and payments tableside on a handheld device, sync to ticket rail', cadence: 'event', automatable: true, requiresTier: 'pro' },
  { id: 'hosp.bar.order.split_check',         industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'service',           microElement: 'Order Entry',     task: 'Split check by item, seat, or evenly across guests',                            cadence: 'event', automatable: true, requiresTier: 'basic' },
  { id: 'hosp.bar.order.fast_menu',           industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'service',           microElement: 'Order Entry',     task: 'Configurable touch-grid menu with categories, modifiers, and favorites for rapid entry', cadence: 'event', automatable: false, requiresTier: 'basic' },
  { id: 'hosp.bar.payments.card_present',     industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'service',           microElement: 'Payments',        task: 'EMV / contactless card-present capture with tokenization',                       cadence: 'event', automatable: true, requiresTier: 'pro' },
  { id: 'hosp.bar.inventory.realtime_depletion', industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'inbound_logistics', microElement: 'Inventory',    task: 'Real-time inventory decrement on order send',                                    cadence: 'event', automatable: true, requiresTier: 'pro' },
  { id: 'hosp.bar.inventory.auto_86',         industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'operations',        microElement: 'Inventory',       task: 'Auto-86 menu items when a recipe component reaches zero on hand',                cadence: 'event', automatable: true, requiresTier: 'pro' },
  { id: 'hosp.bar.inventory.waste_log',       industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'operations',        microElement: 'Waste Log',       task: 'Log spillage / waste against specific SKUs and reasons',                         cadence: 'daily', automatable: true, requiresTier: 'basic' },
  { id: 'hosp.bar.costing.pour_cost_target',  industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'technology',        microElement: 'Cost Control',    task: 'Calculate pour cost % vs. target and flag overages',                             cadence: 'daily', automatable: true, requiresTier: 'pro' },
  { id: 'hosp.bar.costing.menu_margin',       industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'technology',        microElement: 'Cost Control',    task: 'Per-item food / beverage cost and contribution margin',                          cadence: 'daily', automatable: true, requiresTier: 'pro' },
  { id: 'hosp.bar.integrations.pms_room_charge', industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'technology',     microElement: 'Integrations',    task: 'Post tab to a guest folio via PMS room-charge bridge',                           cadence: 'event', automatable: true, requiresTier: 'enterprise' },
  { id: 'hosp.bar.integrations.accounting_export', industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'technology',   microElement: 'Integrations',    task: 'Daily sales journal export to accounting GL',                                    cadence: 'daily', automatable: true, requiresTier: 'pro' },
  { id: 'hosp.bar.analytics.top_items',       industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'technology',        microElement: 'Analytics',       task: 'Top-selling items, dayparts, and category mix report',                           cadence: 'daily', automatable: true, requiresTier: 'basic' },
  { id: 'hosp.bar.analytics.labor_vs_sales',  industryId: 'tertiary.hospitality.bar_nightlife', valueChainStage: 'human_resources',   microElement: 'Analytics',       task: 'Labor cost as % of net sales by shift',                                          cadence: 'daily', automatable: true, requiresTier: 'pro' },
  // ── Cross-restaurant POS basics (fine dining + diner) ──
  { id: 'hosp.fd.pos.split_check',       industryId: 'tertiary.hospitality.fine_dining', valueChainStage: 'service', microElement: 'POS',         task: 'Split check by seat or course',         cadence: 'event', automatable: true, requiresTier: 'basic' },
  { id: 'hosp.fd.pos.tableside_handheld',industryId: 'tertiary.hospitality.fine_dining', valueChainStage: 'service', microElement: 'POS',         task: 'Tableside ordering on handheld',         cadence: 'event', automatable: true, requiresTier: 'pro' },
  { id: 'hosp.dn.pos.split_check',       industryId: 'tertiary.hospitality.diner',       valueChainStage: 'service', microElement: 'POS',         task: 'Split check at counter or booth',        cadence: 'event', automatable: true, requiresTier: 'basic' },
  { id: 'hosp.dn.pos.handheld',          industryId: 'tertiary.hospitality.diner',       valueChainStage: 'service', microElement: 'POS',         task: 'Handheld order entry',                   cadence: 'event', automatable: true, requiresTier: 'basic' },
  // ============================================================
  // OPERATIONAL REALITY EXPANSION PACK — 1000-room resort scale
  // ============================================================
  // 1. FACILITIES & CMMS (Engineering & Life Safety)
  { id: 'hosp.lodging.cmms.preventive_maintenance', industryId: 'tertiary.hospitality.lodging', valueChainStage: 'operations', microElement: 'facilities', task: 'Log and enforce preventive maintenance schedules (HVAC filters, walk-in cooler gaskets, boiler descaling)',         cadence: 'daily',   automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.lodging.cmms.loto_safety_log',        industryId: 'tertiary.hospitality.lodging', valueChainStage: 'operations', microElement: 'compliance', task: 'Digital sign-off for Lock-Out/Tag-Out (LOTO) procedures on heavy mechanical / laundry equipment',                  cadence: 'event',   automatable: false, requiresTier: 'enterprise' },
  { id: 'hosp.lodging.compliance.life_safety_audit',industryId: 'tertiary.hospitality.lodging', valueChainStage: 'operations', microElement: 'compliance', task: 'Automated compliance tracking for NFPA 101, fire suppression hoods, and quarterly sprinkler inspections',          cadence: 'monthly', automatable: true,  requiresTier: 'enterprise' },
  // 2. HOUSEKEEPING & ENVIRONMENTAL SERVICES
  { id: 'hosp.lodging.housekeeping.area_inventory',     industryId: 'tertiary.hospitality.lodging', valueChainStage: 'operations', microElement: 'inventory',  task: 'Track Area Inventory Lists and housekeeping cart par levels (linens, amenities, chemical agents)',          cadence: 'daily',  automatable: false, requiresTier: 'basic' },
  { id: 'hosp.lodging.housekeeping.chemical_manifest',  industryId: 'tertiary.hospitality.lodging', valueChainStage: 'operations', microElement: 'compliance', task: 'Log and track hazardous chemical storage zones, FIFO rotation, and biological cross-contamination prevention cloths', cadence: 'weekly', automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.lodging.housekeeping.dynamic_par_calc',   industryId: 'tertiary.hospitality.lodging', valueChainStage: 'operations', microElement: 'inventory',  task: 'Auto-recalculate required linen and amenity par levels based on live 7-day PMS occupancy projections',      cadence: 'daily',  automatable: true,  requiresTier: 'enterprise' },
  // 3. HIGH-VOLUME F&B (Kitchen & Dining Reality)
  { id: 'hosp.fnb.kds.zone_routing',           industryId: 'tertiary.hospitality.fine_dining', valueChainStage: 'operations', microElement: 'kitchen',    task: 'Splinter incoming POS tickets and route items to specific KDS zones (broiler, fry, garde manger) with expeditor sync', cadence: 'event',  automatable: true,  requiresTier: 'pro' },
  { id: 'hosp.fnb.inventory.tabletop_attrition', industryId: 'tertiary.hospitality.fine_dining', valueChainStage: 'procurement', microElement: 'inventory', task: 'Track breakage and loss rates against mathematical par levels for highly fragile glassware and flatware micro-inventory', cadence: 'weekly', automatable: true, requiresTier: 'pro' },
  { id: 'hosp.fnb.compliance.health_logs',     industryId: 'tertiary.hospitality.diner',       valueChainStage: 'operations', microElement: 'compliance', task: 'Mandatory digital logging for line cold-holding temperatures, walk-in thermometer checks, and grease trap manifests',  cadence: 'daily',  automatable: false, requiresTier: 'pro' },
];
