import type { NanoBite } from '../types';

// Phase 3a — Logistics operational nano-bites
export const LOGISTICS_BITES: NanoBite[] = [
  { id: 'log.trans.dispatch', industryId: 'tertiary.logistics.transportation', valueChainStage: 'operations', microElement: "Dispatch", task: "Auto-assign loads to drivers by HOS availability", cadence: 'daily', automatable: true },
  { id: 'log.trans.route', industryId: 'tertiary.logistics.transportation', valueChainStage: 'outbound_logistics', microElement: "Route Optimization", task: "Re-calc route ETAs against traffic feeds", cadence: 'event', automatable: true },
  { id: 'log.trans.eld', industryId: 'tertiary.logistics.transportation', valueChainStage: 'operations', microElement: "ELD Sync", task: "Pull ELD hours-of-service & flag violations", cadence: 'daily', automatable: true },
  { id: 'log.trans.bol', industryId: 'tertiary.logistics.transportation', valueChainStage: 'outbound_logistics', microElement: "BOL", task: "Generate Bill of Lading at pickup", cadence: 'event', automatable: true },
  { id: 'log.trans.pod', industryId: 'tertiary.logistics.transportation', valueChainStage: 'service', microElement: "POD Capture", task: "Capture signed proof-of-delivery photo", cadence: 'event', automatable: true },
  { id: 'log.trans.fuel', industryId: 'tertiary.logistics.transportation', valueChainStage: 'procurement', microElement: "Fuel Card", task: "Reconcile IFTA fuel card transactions", cadence: 'weekly', automatable: true },
  { id: 'log.cross.inbound', industryId: 'tertiary.logistics.cross_docking', valueChainStage: 'inbound_logistics', microElement: "Inbound Scan", task: "Scan inbound trailer manifest", cadence: 'event', automatable: true },
  { id: 'log.cross.sort', industryId: 'tertiary.logistics.cross_docking', valueChainStage: 'operations', microElement: "Sort Lane", task: "Auto-route freight to outbound lane by SKU", cadence: 'event', automatable: true },
  { id: 'log.cross.dwell', industryId: 'tertiary.logistics.cross_docking', valueChainStage: 'operations', microElement: "Dwell Time", task: "Track dock door dwell time per trailer", cadence: 'daily', automatable: true },
  { id: 'log.cross.short', industryId: 'tertiary.logistics.cross_docking', valueChainStage: 'operations', microElement: "Short/Damage", task: "Log shortage/damage exceptions", cadence: 'event', automatable: true },
  { id: 'log.cross.outbound', industryId: 'tertiary.logistics.cross_docking', valueChainStage: 'outbound_logistics', microElement: "Outbound Load", task: "Confirm outbound load before seal", cadence: 'event', automatable: true },
  { id: 'log.truck.dvir', industryId: 'tertiary.logistics.trucking', valueChainStage: 'operations', microElement: "DVIR", task: "Driver Vehicle Inspection Report (pre/post-trip)", cadence: 'daily', automatable: true },
  { id: 'log.truck.maint', industryId: 'tertiary.logistics.trucking', valueChainStage: 'operations', microElement: "Preventive Maint", task: "Auto-schedule PM by mileage/engine hours", cadence: 'weekly', automatable: true },
  { id: 'log.truck.geofence', industryId: 'tertiary.logistics.trucking', valueChainStage: 'operations', microElement: "Geofence", task: "Geofence arrival/departure stamps", cadence: 'event', automatable: true },
  { id: 'log.truck.detention', industryId: 'tertiary.logistics.trucking', valueChainStage: 'service', microElement: "Detention", task: "Calc detention fees on dwell > threshold", cadence: 'event', automatable: true },
  { id: 'log.truck.settlement', industryId: 'tertiary.logistics.trucking', valueChainStage: 'infrastructure', microElement: "Driver Pay", task: "Driver settlement from completed loads", cadence: 'weekly', automatable: true },
  { id: 'log.truck.factoring', industryId: 'tertiary.logistics.trucking', valueChainStage: 'infrastructure', microElement: "Factoring", task: "Submit invoices to factoring company", cadence: 'weekly', automatable: true, requiresTier: 'pro' },
  { id: 'log.wh.receive', industryId: 'tertiary.logistics.warehousing', valueChainStage: 'inbound_logistics', microElement: "Receiving", task: "ASN-driven receiving + putaway suggestion", cadence: 'daily', automatable: true },
  { id: 'log.wh.putaway', industryId: 'tertiary.logistics.warehousing', valueChainStage: 'operations', microElement: "Putaway", task: "Directed putaway by velocity slot", cadence: 'daily', automatable: true },
  { id: 'log.wh.cycle', industryId: 'tertiary.logistics.warehousing', valueChainStage: 'operations', microElement: "Cycle Count", task: "ABC cycle count cadence enforcement", cadence: 'weekly', automatable: true },
  { id: 'log.wh.pick', industryId: 'tertiary.logistics.warehousing', valueChainStage: 'outbound_logistics', microElement: "Pick Wave", task: "Wave pick generation by carrier cutoff", cadence: 'daily', automatable: true },
  { id: 'log.wh.pack', industryId: 'tertiary.logistics.warehousing', valueChainStage: 'outbound_logistics', microElement: "Pack & Ship", task: "Cartonization + label print", cadence: 'event', automatable: true },
  { id: 'log.wh.slot', industryId: 'tertiary.logistics.warehousing', valueChainStage: 'operations', microElement: "Slotting", task: "Re-slot SKUs by 30-day velocity", cadence: 'monthly', automatable: true, requiresTier: 'pro' },
  { id: 'log.lm.route', industryId: 'tertiary.logistics.last_mile', valueChainStage: 'outbound_logistics', microElement: "Route Build", task: "Build last-mile route with stop sequencing", cadence: 'daily', automatable: true },
  { id: 'log.lm.eta', industryId: 'tertiary.logistics.last_mile', valueChainStage: 'service', microElement: "Customer ETA", task: "SMS dynamic ETA window to recipient", cadence: 'event', automatable: true },
  { id: 'log.lm.proof', industryId: 'tertiary.logistics.last_mile', valueChainStage: 'service', microElement: "Proof", task: "Photo + signature proof-of-delivery", cadence: 'event', automatable: true },
  { id: 'log.lm.failed', industryId: 'tertiary.logistics.last_mile', valueChainStage: 'service', microElement: "Failed Attempt", task: "Log failed delivery & schedule retry", cadence: 'event', automatable: true },
  { id: 'log.lm.return', industryId: 'tertiary.logistics.last_mile', valueChainStage: 'outbound_logistics', microElement: "Returns", task: "Reverse-logistics pickup ticket", cadence: 'event', automatable: true },
  { id: 'log.cold.temp', industryId: 'tertiary.logistics.cold_chain', valueChainStage: 'operations', microElement: "Temp Log", task: "Continuous temperature telemetry log", cadence: 'daily', automatable: true, requiresTier: 'pro' },
  { id: 'log.cold.alert', industryId: 'tertiary.logistics.cold_chain', valueChainStage: 'operations', microElement: "Excursion Alert", task: "Alert on temperature excursion > threshold", cadence: 'event', automatable: true, requiresTier: 'pro' },
  { id: 'log.cold.precool', industryId: 'tertiary.logistics.cold_chain', valueChainStage: 'inbound_logistics', microElement: "Pre-Cool", task: "Pre-cool trailer before load", cadence: 'event', automatable: true },
  { id: 'log.cold.haccp', industryId: 'tertiary.logistics.cold_chain', valueChainStage: 'infrastructure', microElement: "HACCP Log", task: "HACCP compliance audit trail", cadence: 'weekly', automatable: true, requiresTier: 'enterprise' },
  { id: 'log.cold.chain', industryId: 'tertiary.logistics.cold_chain', valueChainStage: 'operations', microElement: "Chain Custody", task: "Chain-of-custody handoff signatures", cadence: 'event', automatable: true },
];
