import type { NanoBite } from '../types';

// Phase 3a — Retail sub-vertical operational nano-bites
export const RETAIL_EXTENDED_BITES: NanoBite[] = [
  { id: 'ret.fash.size', industryId: 'tertiary.retail.fashion_apparel', valueChainStage: 'operations', microElement: "Size Matrix", task: "Size/color matrix inventory view", cadence: 'daily', automatable: true },
  { id: 'ret.fash.fitting', industryId: 'tertiary.retail.fashion_apparel', valueChainStage: 'service', microElement: "Fitting Room", task: "Fitting-room item count", cadence: 'event', automatable: false },
  { id: 'ret.fash.markdown', industryId: 'tertiary.retail.fashion_apparel', valueChainStage: 'marketing_sales', microElement: "Markdown", task: "Auto-markdown on age-of-stock", cadence: 'weekly', automatable: true },
  { id: 'ret.fash.season', industryId: 'tertiary.retail.fashion_apparel', valueChainStage: 'marketing_sales', microElement: "Seasonal Reset", task: "Seasonal floor reset & visual merch", cadence: 'monthly', automatable: true },
  { id: 'ret.fash.return', industryId: 'tertiary.retail.fashion_apparel', valueChainStage: 'service', microElement: "Returns", task: "Returns-fraud check at POS", cadence: 'event', automatable: true },
  { id: 'ret.elec.serial', industryId: 'tertiary.retail.electronics', valueChainStage: 'operations', microElement: "Serial Tracking", task: "Serial-number capture at sale", cadence: 'event', automatable: true },
  { id: 'ret.elec.warranty', industryId: 'tertiary.retail.electronics', valueChainStage: 'service', microElement: "Warranty", task: "Attach warranty / service plan", cadence: 'event', automatable: true },
  { id: 'ret.elec.trade', industryId: 'tertiary.retail.electronics', valueChainStage: 'inbound_logistics', microElement: "Trade-In", task: "Trade-in valuation & intake", cadence: 'event', automatable: true },
  { id: 'ret.elec.demo', industryId: 'tertiary.retail.electronics', valueChainStage: 'operations', microElement: "Demo Stock", task: "Demo-unit inventory carve-out", cadence: 'weekly', automatable: true },
  { id: 'ret.elec.fraud', industryId: 'tertiary.retail.electronics', valueChainStage: 'operations', microElement: "Fraud Check", task: "High-ticket fraud check at POS", cadence: 'event', automatable: true },
  { id: 'ret.furn.deliver', industryId: 'tertiary.retail.furniture', valueChainStage: 'outbound_logistics', microElement: "Delivery Schedule", task: "White-glove delivery scheduling", cadence: 'event', automatable: true },
  { id: 'ret.furn.config', industryId: 'tertiary.retail.furniture', valueChainStage: 'operations', microElement: "Configurator", task: "SKU configurator (fabric/finish)", cadence: 'event', automatable: true },
  { id: 'ret.furn.lead', industryId: 'tertiary.retail.furniture', valueChainStage: 'procurement', microElement: "Lead Time", task: "Vendor lead-time tracking", cadence: 'weekly', automatable: true },
  { id: 'ret.furn.deposit', industryId: 'tertiary.retail.furniture', valueChainStage: 'marketing_sales', microElement: "Deposit", task: "Special-order deposit handling", cadence: 'event', automatable: true },
  { id: 'ret.furn.assembly', industryId: 'tertiary.retail.furniture', valueChainStage: 'service', microElement: "Assembly", task: "In-home assembly job ticket", cadence: 'event', automatable: false },
  { id: 'ret.jew.appraise', industryId: 'tertiary.retail.jewelry', valueChainStage: 'operations', microElement: "Appraisal", task: "GIA appraisal capture per item", cadence: 'event', automatable: false },
  { id: 'ret.jew.repair', industryId: 'tertiary.retail.jewelry', valueChainStage: 'service', microElement: "Repair Ticket", task: "Repair intake & ticket", cadence: 'event', automatable: false },
  { id: 'ret.jew.layaway', industryId: 'tertiary.retail.jewelry', valueChainStage: 'marketing_sales', microElement: "Layaway", task: "Layaway plan management", cadence: 'weekly', automatable: true },
  { id: 'ret.jew.tray', industryId: 'tertiary.retail.jewelry', valueChainStage: 'operations', microElement: "Tray Audit", task: "Open/close tray audit", cadence: 'daily', automatable: true },
  { id: 'ret.jew.kyc', industryId: 'tertiary.retail.jewelry', valueChainStage: 'infrastructure', microElement: "High-Value KYC", task: "KYC on high-value cash sale", cadence: 'event', automatable: true, requiresTier: 'pro' },
  { id: 'ret.sport.rental', industryId: 'tertiary.retail.sporting_goods', valueChainStage: 'marketing_sales', microElement: "Rental", task: "Rental gear check-out / check-in", cadence: 'event', automatable: true },
  { id: 'ret.sport.tune', industryId: 'tertiary.retail.sporting_goods', valueChainStage: 'service', microElement: "Tune Shop", task: "Bike/ski tune-shop work order", cadence: 'event', automatable: false },
  { id: 'ret.sport.season', industryId: 'tertiary.retail.sporting_goods', valueChainStage: 'operations', microElement: "Seasonal", task: "Seasonal SKU activation", cadence: 'monthly', automatable: true },
  { id: 'ret.sport.event', industryId: 'tertiary.retail.sporting_goods', valueChainStage: 'marketing_sales', microElement: "Event Pop-Up", task: "Mobile pop-up at event", cadence: 'event', automatable: true },
  { id: 'ret.sport.warranty', industryId: 'tertiary.retail.sporting_goods', valueChainStage: 'service', microElement: "Warranty Claim", task: "Manufacturer warranty claim", cadence: 'event', automatable: true },
  { id: 'ret.beauty.tester', industryId: 'tertiary.retail.beauty_cosmetics', valueChainStage: 'operations', microElement: "Tester", task: "Tester inventory carve-out", cadence: 'weekly', automatable: true },
  { id: 'ret.beauty.batch', industryId: 'tertiary.retail.beauty_cosmetics', valueChainStage: 'inbound_logistics', microElement: "Batch Lot", task: "Batch/lot expiry tracking", cadence: 'daily', automatable: true },
  { id: 'ret.beauty.book', industryId: 'tertiary.retail.beauty_cosmetics', valueChainStage: 'marketing_sales', microElement: "Service Booking", task: "In-store service booking (brow/lash)", cadence: 'event', automatable: true },
  { id: 'ret.beauty.loyalty', industryId: 'tertiary.retail.beauty_cosmetics', valueChainStage: 'marketing_sales', microElement: "Loyalty", task: "Tiered loyalty point accrual", cadence: 'event', automatable: true },
  { id: 'ret.beauty.gwp', industryId: 'tertiary.retail.beauty_cosmetics', valueChainStage: 'marketing_sales', microElement: "GWP", task: "Gift-with-purchase rule engine", cadence: 'event', automatable: true },
];
