import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { AlertTriangle, CheckCircle, Clock, Eye } from 'lucide-react';

interface RemediationPlan {
  id: string;
  title: string;
  agent_name: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  status: 'pending' | 'approved' | 'rejected' | 'executed';
  explanation: string;
  actions: string[];
  created_at: string;
}

interface SecurityCommandCenterProps {
  remediationPlans: RemediationPlan[];
  onApprove: (planId: string) => void;
  onReject: (planId: string) => void;
}

const getSeverityColor = (severity: string) => {
  switch (severity) {
    case 'low': return 'bg-blue-100 text-blue-800';
    case 'medium': return 'bg-yellow-100 text-yellow-800';
    case 'high': return 'bg-orange-100 text-orange-800';
    case 'critical': return 'bg-red-100 text-red-800';
    default: return 'bg-gray-100 text-gray-800';
  }
};

const getStatusColor = (status: string) => {
  switch (status) {
    case 'pending': return 'bg-yellow-100 text-yellow-800';
    case 'approved': return 'bg-green-100 text-green-800';
    case 'rejected': return 'bg-red-100 text-red-800';
    case 'executed': return 'bg-blue-100 text-blue-800';
    default: return 'bg-gray-100 text-gray-800';
  }
};

export const SecurityCommandCenter = ({ 
  remediationPlans, 
  onApprove, 
  onReject 
}: SecurityCommandCenterProps) => {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Security Command Center</CardTitle>
        <CardDescription>
          Human oversight and approval for automated remediation plans from Crazy Guardian
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {remediationPlans.map((plan) => (
          <div key={plan.id} className="p-4 border rounded-lg space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-3">
                <AlertTriangle className="h-5 w-5 text-orange-600" />
                <div>
                  <h4 className="font-semibold">{plan.title}</h4>
                  <p className="text-sm text-gray-600">Generated by {plan.agent_name}</p>
                </div>
              </div>
              <div className="flex items-center space-x-2">
                <Badge className={getSeverityColor(plan.severity)}>{plan.severity}</Badge>
                <Badge className={getStatusColor(plan.status)}>{plan.status}</Badge>
              </div>
            </div>

            <div className="bg-blue-50 p-3 rounded border-l-4 border-blue-400">
              <div className="flex items-start space-x-2">
                <Eye className="h-4 w-4 text-blue-600 mt-0.5" />
                <div>
                  <h5 className="font-medium text-blue-800">Crazy Insight Explanation</h5>
                  <p className="text-sm text-blue-700">{plan.explanation}</p>
                </div>
              </div>
            </div>

            <div>
              <h5 className="font-medium mb-2">Proposed Actions:</h5>
              <ul className="space-y-1">
                {plan.actions.map((action, index) => (
                  <li key={index} className="text-sm text-gray-700 flex items-center space-x-2">
                    <div className="w-1.5 h-1.5 bg-gray-400 rounded-full"></div>
                    <span>{action}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="flex items-center justify-between pt-2 border-t">
              <div className="flex items-center space-x-2 text-sm text-gray-500">
                <Clock className="h-4 w-4" />
                <span>{new Date(plan.created_at).toLocaleString()}</span>
              </div>
              
              {plan.status === 'pending' && (
                <div className="flex space-x-2">
                  <Button 
                    size="sm" 
                    variant="outline"
                    onClick={() => onReject(plan.id)}
                  >
                    Reject
                  </Button>
                  <Button 
                    size="sm" 
                    onClick={() => onApprove(plan.id)}
                  >
                    Approve & Execute
                  </Button>
                </div>
              )}
              
              {plan.status === 'executed' && (
                <div className="flex items-center space-x-2 text-green-600">
                  <CheckCircle className="h-4 w-4" />
                  <span className="text-sm font-medium">Executed Successfully</span>
                </div>
              )}
            </div>
          </div>
        ))}
        
        {remediationPlans.length === 0 && (
          <div className="text-center py-8 text-gray-500">
            <CheckCircle className="h-12 w-12 mx-auto mb-3 text-green-600" />
            <p>No pending remediation plans</p>
            <p className="text-sm">All security protocols operating normally</p>
          </div>
        )}
      </CardContent>
    </Card>
  );
};