import type { IndustryNode } from '../types';

export const QUATERNARY_INDUSTRIES: IndustryNode[] = [
  { id: 'quaternary.saas.growth',              parentId: 'quaternary', sector: 'quaternary', label: 'SaaS — Growth (1–10 employees)',     naics: '5112', gics: '4510', tags: ['saas','startup'],          defaultProductionMethod: 'job_shop',        defaultArchetype: 'boutique'    },
  { id: 'quaternary.saas.midmarket',           parentId: 'quaternary', sector: 'quaternary', label: 'SaaS — Mid-Market ($5M–$20M ARR)',   naics: '5112',               tags: ['saas','specialized'],      defaultProductionMethod: 'batch',           defaultArchetype: 'mid_market'  },
  { id: 'quaternary.saas.enterprise',          parentId: 'quaternary', sector: 'quaternary', label: 'SaaS — Enterprise ($20M+ ARR)',      naics: '5112',               tags: ['saas','enterprise'],       defaultProductionMethod: 'assembly_line',   defaultArchetype: 'mass_market' },
  { id: 'quaternary.consulting',               parentId: 'quaternary', sector: 'quaternary', label: 'Consulting / Professional Services', naics: '5416',               tags: ['expertise','high_margin'], defaultProductionMethod: 'job_shop',        defaultArchetype: 'boutique'    },
  { id: 'quaternary.rnd',                      parentId: 'quaternary', sector: 'quaternary', label: 'R&D / Scientific Research',          naics: '5417',               tags: ['research','ip'],           defaultProductionMethod: 'job_shop',        defaultArchetype: 'boutique'    },
  { id: 'quaternary.creator.audience_owned',   parentId: 'quaternary', sector: 'quaternary', label: 'Creator — Audience-Owned Media',                                  tags: ['creator','newsletter'],    defaultProductionMethod: 'batch',           defaultArchetype: 'boutique'    },
  { id: 'quaternary.creator.expert',           parentId: 'quaternary', sector: 'quaternary', label: 'Creator — Expert / Authority',                                    tags: ['creator','courses'],       defaultProductionMethod: 'job_shop',        defaultArchetype: 'boutique'    },
  { id: 'quaternary.creator.product',          parentId: 'quaternary', sector: 'quaternary', label: 'Creator — Creator-Led Product',                                   tags: ['creator','cpg','merch'],   defaultProductionMethod: 'batch',           defaultArchetype: 'mid_market'  },
  { id: 'quaternary.creator.algorithm_native', parentId: 'quaternary', sector: 'quaternary', label: 'Creator — Algorithm-Native',                                      tags: ['creator','platform'],      defaultProductionMethod: 'continuous_flow', defaultArchetype: 'mass_market' },
  { id: 'quaternary.creator.hybrid_journalist',parentId: 'quaternary', sector: 'quaternary', label: 'Creator — Hybrid Journalist',                                     tags: ['creator','journalism'],    defaultProductionMethod: 'batch',           defaultArchetype: 'boutique'    },
  { id: 'quaternary.creator.faceless_virtual', parentId: 'quaternary', sector: 'quaternary', label: 'Creator — Faceless / Virtual Persona',                            tags: ['creator','ip_brand'],      defaultProductionMethod: 'batch',           defaultArchetype: 'mid_market'  },
];
