import type { IndustryNode } from '../types';

export const TERTIARY_INDUSTRIES: IndustryNode[] = [
  { id: 'tertiary.retail.boutique', parentId: 'tertiary', sector: 'tertiary', label: 'Retail — Boutique',     naics: '4481',   gics: '2550',   tags: ['boutique','mto','high_margin'],     defaultProductionMethod: 'job_shop',        defaultArchetype: 'boutique',    description: 'Custom, low-volume, high-margin retail.' },
  { id: 'tertiary.retail.mass',     parentId: 'tertiary', sector: 'tertiary', label: 'Retail — Mass Market',  naics: '452',    gics: '2550',   tags: ['mass_market','mts','high_volume'],  defaultProductionMethod: 'assembly_line',   defaultArchetype: 'mass_market' },
  {
    id: 'tertiary.hospitality',
    parentId: 'tertiary',
    sector: 'tertiary',
    label: 'Hospitality',
    naics: '721',
    gics: '253010',
    tags: ['service', 'perishable', 'high_touch', 'spatial_dependent'],
    defaultProductionMethod: 'job_shop',
    defaultArchetype: 'mid_market',
    meta: {
      benchmarks: ['Luxury Tier', 'Upper-Upscale Tier', 'Mid-Scale Tier'],
      tech_stack: ['Property Management System', 'Point-of-Sale', 'Kitchen Display System'],
      telemetry_focus: ['Guest Flow', 'Dwell Time', 'Speed of Service'],
      hardware_layer: ['LiDAR (SPAD)', 'UWB DW3000', 'IMU Wearables'],
      math_layer: ['Quaternions', 'Kalman Filter', 'Particle Filter (AMCL)'],
    },
  },
  {
    id: 'tertiary.hospitality.lodging',
    parentId: 'tertiary.hospitality',
    sector: 'tertiary',
    label: 'Hospitality — Lodging & PMS',
    naics: '7211',
    gics: '253010',
    tags: ['lodging', 'pms', 'multi_channel', 'perishable_inventory'],
    defaultProductionMethod: 'job_shop',
    defaultArchetype: 'mid_market',
    description: 'Hotel and property operations: reservations, front desk, housekeeping, revenue management, and folio billing.',
    meta: {
      tech_stack: ['Property Management System', 'Channel Manager', 'Booking Engine', 'Mobile Key'],
      telemetry_focus: ['ADR', 'Occupancy', 'RevPAR', 'Turn Time'],
    },
  },
  {
    id: 'tertiary.hospitality.bar_nightlife',
    parentId: 'tertiary.hospitality',
    sector: 'tertiary',
    label: 'Hospitality — Bar & Nightlife',
    naics: '7224',
    gics: '253010',
    tags: ['high_velocity', 'tab_based', 'liquid_inventory', 'time_priced'],
    defaultProductionMethod: 'batch',
    defaultArchetype: 'mass_market',
    description: 'High-volume bar, lounge, and nightlife venues: tab management, pour tracking, and time-window pricing.',
    meta: {
      tech_stack: ['Tab Manager', 'Pour Scale Integration', 'Recipe Engine', 'Time-Window Pricing'],
      telemetry_focus: ['Pour Variance', 'Tab Velocity', 'Walkout Rate'],
    },
  },
  { id: 'tertiary.qsr',             parentId: 'tertiary', sector: 'tertiary', label: 'Quick-Service Dining',  naics: '722513',                 tags: ['quick_service','high_velocity'],    defaultProductionMethod: 'batch',           defaultArchetype: 'mass_market' },
  { id: 'tertiary.banking',         parentId: 'tertiary', sector: 'tertiary', label: 'Banking & Financial',   naics: '522',    gics: '40',     tags: ['regulated','service'],              defaultProductionMethod: 'assembly_line',   defaultArchetype: 'mid_market'  },
  { id: 'tertiary.transport',       parentId: 'tertiary', sector: 'tertiary', label: 'Transportation & Logistics', naics: '484', gics: '2030', tags: ['logistics','fleet'],               defaultProductionMethod: 'continuous_flow', defaultArchetype: 'mass_market' },
];
