import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
import { Radio, Play, Square, Activity, Database } from 'lucide-react';
import { useSynapseCredits } from '@/contexts/SynapseCreditsContext';

interface FeatureFeed {
  id: string;
  name: string;
  description: string;
  topic: string;
  status: string;
  latency: string;
  subscribers: number;
}

export default function FeatureFeedAccess() {
  const [feeds, setFeeds] = useState<FeatureFeed[]>([]);
  const [activeFeeds, setActiveFeeds] = useState<Set<string>>(new Set());
  const [liveData, setLiveData] = useState<Record<string, any[]>>({});
  const { toast } = useToast();
  const { refreshBalance } = useSynapseCredits();

  useEffect(() => {
    fetchFeeds();
  }, []);

  const fetchFeeds = async () => {
    const { data } = await supabase.from('feature_feeds').select('*').order('name');
    if (data) setFeeds(data);
  };

  const toggleFeed = async (topic: string) => {
    setActiveFeeds(prev => {
      const next = new Set(prev);
      if (next.has(topic)) {
        // Disconnect
        supabase.removeChannel(supabase.channel(topic));
        next.delete(topic);
        toast({ title: 'Disconnected', description: `Unsubscribed from ${topic}` });
      } else {
        // Connect Live Vault Tunnel
        const channel = supabase.channel(topic)
          .on('broadcast', { event: 'vault_update' }, payload => {
            setLiveData(current => ({
              ...current,
              [topic]: [payload.payload, ...(current[topic] || [])].slice(0, 5) // Keep last 5 payloads
            }));
          })
          .subscribe((status) => {
            if (status === 'SUBSCRIBED') {
              toast({ title: 'Connected', description: `Live stream established for ${topic}` });
            }
          });
        next.add(topic);
      }
      return next;
    });

    // Fire a Synapse consumption receipt for connects (vault egress).
    if (!activeFeeds.has(topic)) {
      try {
        const { data: { user } } = await supabase.auth.getUser();
        if (!user?.id) return;
        const ref = `feed_${topic}_${Date.now().toString(36)}`;
        const { data, error } = await supabase.functions.invoke('synapse-controller', {
          body: {
            user_id: user.id,
            client_id: 'IDIA_HUB_FEATURE_FEED',
            intent_type: 'FEATURE_FEED_SUBSCRIBE',
            sub_module_id: topic,
            aca_record_ids: [ref],
            metadata: { topic },
          },
        });
        if (error || (data as any)?.error) {
          toast({ title: 'Receipt warning', description: 'Stream connected but receipt could not be issued.' });
        } else {
          await refreshBalance();
        }
      } catch (err: any) {
        console.error('[FeatureFeedAccess] receipt error', err?.message);
      }
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-2 mb-6">
        <Database className="w-6 h-6 text-primary" />
        <div>
          <h2 className="text-2xl font-bold">Data Vault Feeds</h2>
          <p className="text-muted-foreground">Subscribe to real-time streams generated by the AI Synapse engine.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {feeds.map(feed => {
          const isActive = activeFeeds.has(feed.topic);
          const feedLogs = liveData[feed.topic] || [];

          return (
            <Card key={feed.id} className={`transition-all duration-300 ${isActive ? 'border-primary shadow-md shadow-primary/10' : ''}`}>
              <CardHeader className="pb-3">
                <div className="flex justify-between items-start">
                  <div>
                    <CardTitle className="flex items-center gap-2 text-lg">
                      <Radio className={`w-5 h-5 ${isActive ? 'text-primary animate-pulse' : 'text-muted-foreground'}`} />
                      {feed.name}
                    </CardTitle>
                    <CardDescription className="mt-1">{feed.description}</CardDescription>
                  </div>
                  <Button 
                    variant={isActive ? "destructive" : "default"} 
                    size="sm"
                    onClick={() => toggleFeed(feed.topic)}
                  >
                    {isActive ? <><Square className="w-4 h-4 mr-2 fill-current" /> Stop</> : <><Play className="w-4 h-4 mr-2 fill-current" /> Connect</>}
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                <div className="flex items-center gap-4 mb-4 text-sm">
                  <Badge variant="outline" className="bg-muted">Topic: <code className="ml-1 text-primary">{feed.topic}</code></Badge>
                  <span className="text-muted-foreground flex items-center gap-1"><Activity className="w-3 h-3"/> {feed.latency} latency</span>
                </div>
                
                <div className="bg-slate-950 rounded-lg p-3 h-[140px] overflow-y-auto font-mono text-xs">
                  {!isActive ? (
                    <div className="h-full flex items-center justify-center text-slate-600">Stream disconnected.</div>
                  ) : feedLogs.length === 0 ? (
                    <div className="h-full flex items-center gap-2 text-primary/70">
                      <div className="w-2 h-2 rounded-full bg-primary animate-ping" />
                      Listening to vault stream...
                    </div>
                  ) : (
                    <div className="space-y-2">
                      {feedLogs.map((log, i) => (
                        <div key={i} className="text-green-400 break-all border-b border-slate-800 pb-2">
                          <span className="text-slate-500 mr-2">[{new Date().toLocaleTimeString()}]</span>
                          {JSON.stringify(log)}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
