import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
import { Radio, Play, Square, Activity, Database } from 'lucide-react';
import { useSynapseCredits } from '@/contexts/SynapseCreditsContext';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { Skeleton } from '@/components/ui/skeleton';

interface FeatureFeed {
  id: string;
  name: string;
  description: string;
  topic: string;
  status: string;
  latency: string;
  subscribers: number;
}

export default function FeatureFeedAccess() {
  const [feeds, setFeeds] = useState<FeatureFeed[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeFeeds, setActiveFeeds] = useState<Set<string>>(new Set());
  const [liveData, setLiveData] = useState<Record<string, any[]>>({});
  const { toast } = useToast();
  const { refreshBalance } = useSynapseCredits();

  useEffect(() => {
    fetchFeeds();
  }, []);

  const fetchFeeds = async () => {
    setLoading(true);
    const { data, error } = await supabase.from('feature_feeds').select('*').order('name');
    if (error) {
      setError(error.message);
    } else {
      setFeeds(data ?? []);
      setError(null);
    }
    setLoading(false);
  };

  const toggleFeed = async (topic: string) => {
    setActiveFeeds(prev => {
      const next = new Set(prev);
      if (next.has(topic)) {
        // Disconnect
        supabase.removeChannel(supabase.channel(topic));
        next.delete(topic);
        toast({ title: 'Disconnected', description: `Unsubscribed from ${topic}` });
      } else {
        // Connect Live Vault Tunnel
        const channel = supabase.channel(topic)
          .on('broadcast', { event: 'vault_update' }, payload => {
            setLiveData(current => ({
              ...current,
              [topic]: [payload.payload, ...(current[topic] || [])].slice(0, 5) // Keep last 5 payloads
            }));
          })
          .subscribe((status) => {
            if (status === 'SUBSCRIBED') {
              toast({ title: 'Connected', description: `Live stream established for ${topic}` });
            }
          });
        next.add(topic);
      }
      return next;
    });

    // NOTE: Subscribing to a realtime channel is not an audited data egress
    // and must not synthesize an ACA record. A Synapse receipt is only
    // issued when the Synapse engine publishes a real vault payload that
    // carries genuine aca_record_ids.
  };

  return (
    <TooltipProvider delayDuration={150}>
    <div className="space-y-6">
      <div className="flex items-center gap-2 mb-6">
        <Database className="w-6 h-6 text-primary" />
        <div>
          <h2 className="text-2xl font-bold">Data Vault Feeds</h2>
          <p className="text-muted-foreground">Subscribe to real-time streams generated by the AI Synapse engine.</p>
        </div>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {[0,1,2,3].map(i => <Skeleton key={i} className="h-56 w-full" />)}
        </div>
      ) : error ? (
        <Card><CardContent className="p-6 text-sm text-destructive">
          Failed to load feeds: {error}
        </CardContent></Card>
      ) : feeds.length === 0 ? (
        <Card><CardContent className="p-8 text-center text-muted-foreground">
          <Radio className="w-8 h-8 mx-auto mb-3 opacity-40" />
          <p className="font-medium">No vault feeds published yet.</p>
          <p className="text-xs mt-1">Feeds appear here once the Synapse engine registers them in <code>feature_feeds</code>.</p>
        </CardContent></Card>
      ) : (
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {feeds.map(feed => {
          const isActive = activeFeeds.has(feed.topic);
          const feedLogs = liveData[feed.topic] || [];

          return (
            <Card key={feed.id} className={`transition-all duration-300 ${isActive ? 'border-primary shadow-md shadow-primary/10' : ''}`}>
              <CardHeader className="pb-3">
                <div className="flex justify-between items-start">
                  <div>
                    <CardTitle className="flex items-center gap-2 text-lg">
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <span tabIndex={0} className="inline-flex">
                            <Radio className={`w-5 h-5 ${isActive ? 'text-primary animate-pulse' : 'text-muted-foreground'}`} />
                          </span>
                        </TooltipTrigger>
                        <TooltipContent>
                          {isActive ? 'Live: subscribed to Supabase Realtime channel' : 'Idle: not subscribed to this vault channel'}
                        </TooltipContent>
                      </Tooltip>
                      {feed.name}
                    </CardTitle>
                    <CardDescription className="mt-1">{feed.description}</CardDescription>
                  </div>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        variant={isActive ? "destructive" : "default"}
                        size="sm"
                        onClick={() => toggleFeed(feed.topic)}
                      >
                        {isActive ? <><Square className="w-4 h-4 mr-2 fill-current" /> Stop</> : <><Play className="w-4 h-4 mr-2 fill-current" /> Connect</>}
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>
                      {isActive
                        ? 'Disconnect from this realtime channel'
                        : 'Open a Supabase Realtime broadcast subscription to this vault topic. Fires a Synapse consumption receipt on connect.'}
                    </TooltipContent>
                  </Tooltip>
                </div>
              </CardHeader>
              <CardContent>
                <div className="flex items-center gap-4 mb-4 text-sm">
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <span tabIndex={0}>
                        <Badge variant="outline" className="bg-muted">Topic: <code className="ml-1 text-primary">{feed.topic}</code></Badge>
                      </span>
                    </TooltipTrigger>
                    <TooltipContent>Realtime broadcast channel name published by the Synapse engine.</TooltipContent>
                  </Tooltip>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <span tabIndex={0} className="text-muted-foreground flex items-center gap-1">
                        <Activity className="w-3 h-3"/> {feed.latency ?? '—'} latency
                      </span>
                    </TooltipTrigger>
                    <TooltipContent>Publisher's declared end-to-end delivery latency for this feed.</TooltipContent>
                  </Tooltip>
                </div>
                
                <div className="bg-slate-950 rounded-lg p-3 h-[140px] overflow-y-auto font-mono text-xs">
                  {!isActive ? (
                    <div className="h-full flex items-center justify-center text-slate-600">Stream disconnected.</div>
                  ) : feedLogs.length === 0 ? (
                    <div className="h-full flex items-center gap-2 text-primary/70">
                      <div className="w-2 h-2 rounded-full bg-primary animate-ping" />
                      Listening to vault stream...
                    </div>
                  ) : (
                    <div className="space-y-2">
                      {feedLogs.map((log, i) => (
                        <div key={i} className="text-green-400 break-all border-b border-slate-800 pb-2">
                          <span className="text-slate-500 mr-2">[{new Date().toLocaleTimeString()}]</span>
                          {JSON.stringify(log)}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
      )}
    </div>
    </TooltipProvider>
  );
}
