-- ─── Step 1: Taxonomy dictionary tables ───────────────────────────────
CREATE TABLE IF NOT EXISTS public.taxonomy_verticals (
  id          text PRIMARY KEY,
  name        text NOT NULL,
  icon        text,
  color       text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.taxonomy_submodules (
  id           text PRIMARY KEY,
  vertical_id  text NOT NULL REFERENCES public.taxonomy_verticals(id) ON DELETE CASCADE,
  name         text NOT NULL,
  description  text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_taxonomy_submodules_vertical ON public.taxonomy_submodules(vertical_id);

-- ─── Step 2: RLS — public read, service-role write ────────────────────
ALTER TABLE public.taxonomy_verticals  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.taxonomy_submodules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read verticals"  ON public.taxonomy_verticals;
DROP POLICY IF EXISTS "Public can read submodules" ON public.taxonomy_submodules;
CREATE POLICY "Public can read verticals"
  ON public.taxonomy_verticals  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public can read submodules"
  ON public.taxonomy_submodules FOR SELECT TO anon, authenticated USING (true);

DROP TRIGGER IF EXISTS trg_taxonomy_verticals_updated  ON public.taxonomy_verticals;
DROP TRIGGER IF EXISTS trg_taxonomy_submodules_updated ON public.taxonomy_submodules;
CREATE TRIGGER trg_taxonomy_verticals_updated
  BEFORE UPDATE ON public.taxonomy_verticals
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_taxonomy_submodules_updated
  BEFORE UPDATE ON public.taxonomy_submodules
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ─── Step 3: businesses.submodule_id FK ───────────────────────────────
ALTER TABLE public.businesses
  ADD COLUMN IF NOT EXISTS submodule_id text
  REFERENCES public.taxonomy_submodules(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_businesses_submodule ON public.businesses(submodule_id);

-- ─── Step 4: Seeding ─────────────────────────────────────────────────
INSERT INTO public.taxonomy_verticals (id,name,icon,color) VALUES
  ('grocer','Grocer','ShoppingCart','bg-green-500'),
  ('hospitality','Hospitality','Utensils','bg-orange-500'),
  ('logistics','Logistics','Truck','bg-blue-500'),
  ('healthcare','Healthcare','Stethoscope','bg-red-500'),
  ('retail','Retail','Building2','bg-purple-500'),
  ('automotive','Automotive','Car','bg-slate-600'),
  ('fitness','Fitness & Wellness','Dumbbell','bg-pink-500'),
  ('education','Education','GraduationCap','bg-indigo-500'),
  ('entertainment','Entertainment','Gamepad2','bg-yellow-500'),
  ('professional','Professional Services','Briefcase','bg-teal-500'),
  ('manufacturing','Manufacturing','Factory','bg-amber-600'),
  ('travel','Travel & Tourism','Plane','bg-cyan-500'),
  ('agriculture','Agriculture','Leaf','bg-lime-600'),
  ('construction','Construction','Hammer','bg-orange-600'),
  ('energy','Energy & Utilities','Zap','bg-yellow-600'),
  ('financial','Financial Services','Landmark','bg-emerald-600'),
  ('government','Government & Public','Building','bg-blue-700'),
  ('media','Media & Publishing','Tv','bg-rose-500'),
  ('telecom','Telecommunications','Radio','bg-violet-500'),
  ('realestate','Real Estate','Home','bg-amber-500'),
  ('nonprofit','Non-Profit','Heart','bg-red-400'),
  ('marine','Marine & Maritime','Ship','bg-sky-600'),
  ('aviation','Aviation','Plane','bg-sky-500'),
  ('mining','Mining & Extraction','Pickaxe','bg-stone-600'),
  ('security','Security Services','Lock','bg-gray-700'),
  ('events','Event Services','Calendar','bg-fuchsia-500'),
  ('personal','Personal Services','Scissors','bg-pink-400'),
  ('pet','Pet Services','PawPrint','bg-orange-400'),
  ('funeral','Funeral Services','Flower2','bg-gray-500'),
  ('cannabis','Cannabis','Cannabis','bg-green-600'),
  ('ecommerce','E-Commerce','Globe','bg-blue-400'),
  ('foodbev','Food & Beverage Production','Beer','bg-amber-500')
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, color=EXCLUDED.color;

INSERT INTO public.taxonomy_submodules (id,vertical_id,name,description) VALUES
  ('grocer-club','grocer','Club Store','Membership-based wholesale'),
  ('grocer-marketplace','grocer','Marketplace','Multi-vendor grocery'),
  ('grocer-supercenter','grocer','Super Center','Full-service supermarket'),
  ('grocer-convenience','grocer','Convenience','Quick-stop essentials'),
  ('grocer-organic','grocer','Organic & Natural','Health-focused grocery'),
  ('grocer-butcher','grocer','Butcher Shop','Specialty meats'),
  ('hosp-fine-dining','hospitality','Fine Dining','Upscale restaurant service'),
  ('hosp-diner','hospitality','Diner','Casual dining experience'),
  ('hosp-hotel','hospitality','Hotel','Lodging & room service'),
  ('hosp-home','hospitality','Home Services','In-home hospitality'),
  ('hosp-theme-park','hospitality','Theme Park','Entertainment venues'),
  ('hosp-cafe','hospitality','Café & Bakery','Coffee & pastries'),
  ('hosp-bar','hospitality','Bar & Lounge','Beverage service'),
  ('hosp-catering','hospitality','Catering','Event food service'),
  ('log-transportation','logistics','Transportation','Fleet management'),
  ('log-cross-docking','logistics','Cross Docking','Transfer operations'),
  ('log-trucking','logistics','Trucking','Long-haul freight'),
  ('log-warehouse','logistics','Warehousing','Storage facilities'),
  ('log-last-mile','logistics','Last Mile','Final delivery'),
  ('log-cold-chain','logistics','Cold Chain','Temperature-controlled'),
  ('health-clinic','healthcare','Clinic','Outpatient care'),
  ('health-hospital','healthcare','Hospital','Inpatient services'),
  ('health-pharmacy','healthcare','Pharmacy','Prescription services'),
  ('health-dental','healthcare','Dental','Oral healthcare'),
  ('health-optometry','healthcare','Optometry','Vision care'),
  ('health-veterinary','healthcare','Veterinary','Animal care'),
  ('health-mental','healthcare','Mental Health','Counseling & therapy'),
  ('health-rehab','healthcare','Rehabilitation','Recovery services'),
  ('retail-fashion','retail','Fashion & Apparel','Clothing stores'),
  ('retail-electronics','retail','Electronics','Tech retail'),
  ('retail-furniture','retail','Furniture','Home furnishings'),
  ('retail-jewelry','retail','Jewelry','Luxury goods'),
  ('retail-sporting','retail','Sporting Goods','Athletic equipment'),
  ('retail-beauty','retail','Beauty & Cosmetics','Personal care'),
  ('auto-dealership','automotive','Dealership','Vehicle sales'),
  ('auto-service','automotive','Service Center','Repairs & maintenance'),
  ('auto-parts','automotive','Parts Store','Auto parts retail'),
  ('auto-rental','automotive','Rental','Vehicle rentals'),
  ('auto-wash','automotive','Car Wash','Cleaning services'),
  ('auto-fleet','automotive','Fleet Management','Corporate vehicles'),
  ('fit-gym','fitness','Gym','Fitness center'),
  ('fit-yoga','fitness','Yoga Studio','Mind-body wellness'),
  ('fit-spa','fitness','Spa','Relaxation services'),
  ('fit-martial-arts','fitness','Martial Arts','Combat training'),
  ('fit-swimming','fitness','Swimming','Aquatic center'),
  ('fit-crossfit','fitness','CrossFit','High-intensity training'),
  ('edu-school','education','K-12 School','Primary education'),
  ('edu-university','education','University','Higher education'),
  ('edu-tutoring','education','Tutoring Center','Academic support'),
  ('edu-vocational','education','Vocational','Trade schools'),
  ('edu-daycare','education','Daycare','Early childhood'),
  ('edu-online','education','Online Learning','E-learning platforms'),
  ('ent-cinema','entertainment','Cinema','Movie theaters'),
  ('ent-arcade','entertainment','Arcade','Gaming venue'),
  ('ent-bowling','entertainment','Bowling','Recreation center'),
  ('ent-concert','entertainment','Concert Venue','Live performances'),
  ('ent-museum','entertainment','Museum','Cultural exhibits'),
  ('ent-casino','entertainment','Casino','Gaming entertainment'),
  ('prof-legal','professional','Legal','Law offices'),
  ('prof-accounting','professional','Accounting','Financial services'),
  ('prof-consulting','professional','Consulting','Business advisory'),
  ('prof-marketing','professional','Marketing Agency','Advertising services'),
  ('prof-architecture','professional','Architecture','Design services'),
  ('mfg-assembly','manufacturing','Assembly','Product assembly'),
  ('mfg-processing','manufacturing','Processing','Raw materials'),
  ('mfg-packaging','manufacturing','Packaging','Product packaging'),
  ('mfg-quality','manufacturing','Quality Control','QA operations'),
  ('mfg-textile','manufacturing','Textile','Fabric production'),
  ('travel-agency','travel','Travel Agency','Trip planning'),
  ('travel-airline','travel','Airline','Air travel'),
  ('travel-cruise','travel','Cruise','Sea travel'),
  ('travel-tour','travel','Tour Operator','Guided tours'),
  ('travel-resort','travel','Resort','Vacation destinations'),
  ('agri-farming','agriculture','Farming','Crop production'),
  ('agri-ranching','agriculture','Ranching','Livestock management'),
  ('agri-aquaculture','agriculture','Aquaculture','Fish farming'),
  ('agri-greenhouse','agriculture','Greenhouse','Controlled environment'),
  ('agri-equipment','agriculture','Equipment Rental','Farm machinery'),
  ('const-general','construction','General Contractor','Building services'),
  ('const-electrical','construction','Electrical','Wiring & power'),
  ('const-plumbing','construction','Plumbing','Water systems'),
  ('const-hvac','construction','HVAC','Climate control'),
  ('const-landscaping','construction','Landscaping','Outdoor spaces'),
  ('const-roofing','construction','Roofing','Roof installation'),
  ('energy-solar','energy','Solar','Solar power'),
  ('energy-wind','energy','Wind','Wind energy'),
  ('energy-oil-gas','energy','Oil & Gas','Petroleum services'),
  ('energy-electric','energy','Electric Utility','Power distribution'),
  ('energy-water','energy','Water Treatment','Water services'),
  ('fin-banking','financial','Banking','Bank services'),
  ('fin-credit-union','financial','Credit Union','Member banking'),
  ('fin-investment','financial','Investment','Wealth management'),
  ('fin-mortgage','financial','Mortgage','Home lending'),
  ('fin-fintech','financial','Fintech','Digital finance'),
  ('fin-insurance','financial','Insurance','Coverage services'),
  ('gov-municipal','government','Municipal','City services'),
  ('gov-federal','government','Federal','National agencies'),
  ('gov-courts','government','Courts','Legal system'),
  ('gov-dmv','government','DMV','Vehicle registration'),
  ('gov-parks','government','Parks & Recreation','Public spaces'),
  ('media-print','media','Print Media','Newspapers & magazines'),
  ('media-broadcast','media','Broadcasting','TV & radio'),
  ('media-streaming','media','Streaming','Digital content'),
  ('media-podcast','media','Podcasting','Audio content'),
  ('media-news','media','News','News outlets'),
  ('tel-isp','telecom','ISP','Internet service'),
  ('tel-mobile','telecom','Mobile Carrier','Cellular service'),
  ('tel-cable','telecom','Cable','Cable TV & internet'),
  ('tel-satellite','telecom','Satellite','Satellite communications'),
  ('tel-datacenter','telecom','Data Centers','Server facilities'),
  ('re-property','realestate','Property Management','Building management'),
  ('re-leasing','realestate','Leasing','Rental services'),
  ('re-brokerage','realestate','Brokerage','Sales agents'),
  ('re-appraisal','realestate','Appraisal','Property valuation'),
  ('re-title','realestate','Title','Title services'),
  ('np-charity','nonprofit','Charity','Charitable organization'),
  ('np-foundation','nonprofit','Foundation','Grant-making'),
  ('np-ngo','nonprofit','NGO','Non-governmental org'),
  ('np-religious','nonprofit','Religious','Faith-based org'),
  ('np-community','nonprofit','Community Org','Local groups'),
  ('mar-shipping','marine','Shipping','Cargo transport'),
  ('mar-port','marine','Port Operations','Harbor services'),
  ('mar-boat-sales','marine','Boat Sales','Vessel retail'),
  ('mar-marina','marine','Marina','Docking services'),
  ('mar-fishing','marine','Commercial Fishing','Fishing operations'),
  ('avi-airport','aviation','Airport','Airport operations'),
  ('avi-flight-school','aviation','Flight School','Pilot training'),
  ('avi-charter','aviation','Charter','Private flights'),
  ('avi-maintenance','aviation','Maintenance','Aircraft service'),
  ('avi-cargo','aviation','Air Cargo','Freight transport'),
  ('min-mining','mining','Mining','Mineral extraction'),
  ('min-quarrying','mining','Quarrying','Stone extraction'),
  ('min-drilling','mining','Drilling','Well drilling'),
  ('min-refining','mining','Refining','Material processing'),
  ('sec-private','security','Private Security','Guard services'),
  ('sec-alarm','security','Alarm Systems','Monitoring services'),
  ('sec-surveillance','security','Surveillance','Camera systems'),
  ('sec-cyber','security','Cybersecurity','Digital protection'),
  ('evt-wedding','events','Wedding Planning','Wedding events'),
  ('evt-corporate','events','Corporate Events','Business functions'),
  ('evt-concerts','events','Concerts','Music events'),
  ('evt-festivals','events','Festivals','Public celebrations'),
  ('evt-convention','events','Conventions','Trade shows'),
  ('pers-salon','personal','Salon','Hair styling'),
  ('pers-barbershop','personal','Barbershop','Men''s grooming'),
  ('pers-tattoo','personal','Tattoo','Body art'),
  ('pers-dry-cleaning','personal','Dry Cleaning','Garment care'),
  ('pers-tailoring','personal','Tailoring','Custom clothing'),
  ('pet-store','pet','Pet Store','Pet supplies'),
  ('pet-grooming','pet','Grooming','Pet grooming'),
  ('pet-boarding','pet','Boarding','Pet hotel'),
  ('pet-training','pet','Training','Obedience training'),
  ('pet-daycare','pet','Pet Daycare','Day services'),
  ('fun-home','funeral','Funeral Home','Funeral services'),
  ('fun-cemetery','funeral','Cemetery','Burial grounds'),
  ('fun-cremation','funeral','Cremation','Cremation services'),
  ('fun-memorial','funeral','Memorial','Memorial services'),
  ('can-dispensary','cannabis','Dispensary','Retail cannabis'),
  ('can-cultivation','cannabis','Cultivation','Growing operations'),
  ('can-processing','cannabis','Processing','Product manufacturing'),
  ('can-testing','cannabis','Testing Lab','Quality testing'),
  ('ecom-dropship','ecommerce','Dropshipping','Drop ship model'),
  ('ecom-marketplace','ecommerce','Marketplace Seller','Multi-channel'),
  ('ecom-subscription','ecommerce','Subscription Box','Recurring delivery'),
  ('ecom-digital','ecommerce','Digital Goods','Digital products'),
  ('fb-brewery','foodbev','Brewery','Beer production'),
  ('fb-winery','foodbev','Winery','Wine production'),
  ('fb-distillery','foodbev','Distillery','Spirits production'),
  ('fb-bakery-prod','foodbev','Bakery Production','Baked goods'),
  ('fb-food-truck','foodbev','Food Truck','Mobile food')
ON CONFLICT (id) DO UPDATE SET vertical_id=EXCLUDED.vertical_id, name=EXCLUDED.name, description=EXCLUDED.description;