ALTER TABLE public.businesses
  ADD COLUMN IF NOT EXISTS street_address_1 TEXT,
  ADD COLUMN IF NOT EXISTS street_address_2 TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS state TEXT,
  ADD COLUMN IF NOT EXISTS postal_code TEXT,
  ADD COLUMN IF NOT EXISTS country TEXT DEFAULT 'US';