// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qltkclkghtziwipwxxxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsdGtjbGtnaHR6aXdpcHd4eHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDkzNTgsImV4cCI6MjA2Nzg4NTM1OH0.J3R68H8LkBTyX8qu7WPg37rTOjI1Jt56zX-MHkRt7VU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});